version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:                                                                 
        - make install 
  testing & linting:
    commands:
     - make lint
    commands:
      - echo Lint completed on `date